---
os: linux
dist: xenial
language: generic
env:
  - PDK=release PDK_FRONTEND=noninteractive
  - PDK=nightly PDK_FRONTEND=noninteractive
before_install:
  - ".travis/install_pdk.sh"
script:
  - ".travis/test_script.sh"
branches:
  only:
    - master
notifications:
  email: false
